# Site settings
title: Yusuke Ando a.k.a yando
email: yandod@gmail.com
description: "This is my personal profile website."
baseurl: ""
url : "https://yandod.github.io"
#url: "http://127.0.0.1:4000"
username: yandod
domain: "yandod.github.io"

# Build settings
markdown: redcarpet
redcarpet:
    extensions: [with_toc_data]
permalink: pretty

gems:
  - jekyll-seo-tag
