# Site settings
title: Yusuke Ando a.k.a yando
email: yandod@gmail.com
description: "This is my personal profile website."
baseurl: ""
url: "https://yandod.github.io"
username: yandod
domain: "yandod.github.io"

# Build settings
markdown: redcarpet
permalink: pretty
